# Konfigurasi tombol "Sponsor" pada repositori GitHub.
# Hapus komentar dan isi sesuai akun Anda bila ingin menerima dukungan.
# Dokumentasi: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [SultanZhalifa]
# ko_fi: username
# custom: ["https://saweria.co/username", "https://trakteer.id/username"]
